# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Kōdo No Bōken
author: Yenly Ma
email: yencodes@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Kōdo No Bōken (コードの冒険) translates to Code Adventures.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mindfullycrafts
github_username:  yenly
instagram_username: mindfullycrafts

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
timezone: America/Los_Angeles

gems:
  - jekyll-feed
  - jekyll-coffeescript
  - jekyl-paginate
  - jemoji
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
